# Generated by Django 4.0.3 on 2022-04-08 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('okulzili', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='okulzili',
            name='isPublished',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='okulzili',
            name='description',
            field=models.TimeField(verbose_name='Eklenme Saati'),
        ),
    ]
