# Generated by Django 4.0.4 on 2022-05-11 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('okulzili', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duyurumodel',
            name='description',
            field=models.TextField(max_length=5000, verbose_name='İçerik Bilgisi'),
        ),
    ]
