# Generated by Django 4.0.4 on 2022-05-11 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('okulzili', '0002_alter_duyurumodel_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='CikisMelodiModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cikisMelodi', models.CharField(max_length=50, verbose_name='Öğretmen Zili Melodisi:')),
                ('cikisSesDuzeyi', models.IntegerField(default=50, verbose_name='Ses Düzeyi 0-100:')),
            ],
        ),
        migrations.CreateModel(
            name='OgrenciMelodiModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ogrenciMelodi', models.CharField(max_length=50, verbose_name='Öğrenci Zili Melodisi:')),
                ('ogrenciAnons', models.BooleanField(default=True, verbose_name='Anon Kullan')),
                ('ogrenciAnonsDers1', models.BooleanField(default=False, verbose_name='1.Ders Hariç Diğerlerinde Anons Kullan')),
                ('ogrenciSesDuzeyi', models.IntegerField(default=50, verbose_name='Ses Düzeyi 0-100:')),
            ],
        ),
        migrations.CreateModel(
            name='OgretmenMelodiModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ogretmenMelodi', models.CharField(max_length=50, verbose_name='Öğretmen Zili Melodisi:')),
                ('ogretmenAnons', models.BooleanField(default=True, verbose_name='Anon Kullan')),
                ('ogretmenAnonsDers1', models.BooleanField(default=False, verbose_name='1.Ders Hariç Diğerlerinde Anons Kullan')),
                ('ogretmenSesDuzeyi', models.IntegerField(default=50, verbose_name='Ses Düzeyi 0-100:')),
            ],
        ),
        migrations.CreateModel(
            name='SaatModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ogrenci', models.TimeField(verbose_name='Öğrenci Zili')),
                ('ogretmen', models.TimeField(verbose_name='Öğretmen Zili')),
                ('cikis', models.TimeField(verbose_name='Çıkış Zili')),
                ('sesDuzeyi', models.IntegerField(default=50, verbose_name='Ses Düzeyi 0-100:')),
            ],
        ),
    ]
