# Generated by Django 4.0.4 on 2022-05-11 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('okulzili', '0003_cikismelodimodel_ogrencimelodimodel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='saatmodel',
            name='dersSaati',
            field=models.CharField(default='Tören', max_length=50, verbose_name='Ders Saati'),
        ),
    ]
