# Generated by Django 4.0.4 on 2022-05-11 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('okulzili', '0004_saatmodel_derssaati'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saatmodel',
            name='dersSaati',
            field=models.CharField(default='1. Ders', max_length=50, verbose_name='Ders Saati'),
        ),
    ]
